export const initialDesks = [
  { id: 'A1', row: 'A', status: 'free' },
  { id: 'A2', row: 'A', status: 'free' },
  { id: 'A3', row: 'A', status: 'free' },
  { id: 'A4', row: 'A', status: 'free' },
  { id: 'B1', row: 'B', status: 'free' },
  { id: 'B2', row: 'B', status: 'occupied', studentName: 'Rahul', checkedInAt: Date.now() - 1000 * 60 * 47 },
  { id: 'B3', row: 'B', status: 'free' },
  { id: 'B4', row: 'B', status: 'occupied', studentName: 'Arjun', checkedInAt: Date.now() - 1000 * 60 * 22 },
  { id: 'C1', row: 'C', status: 'free' },
  { id: 'C2', row: 'C', status: 'away', studentName: 'Priya', checkedInAt: Date.now() - 1000 * 60 * 30, awayAt: Date.now() - 1000 * 60 * 12 },
  { id: 'C3', row: 'C', status: 'occupied', studentName: 'Meera', checkedInAt: Date.now() - 1000 * 60 * 8 },
  { id: 'C4', row: 'C', status: 'free' },
  { id: 'D1', row: 'D', status: 'occupied', studentName: 'Karan', checkedInAt: Date.now() - 1000 * 60 * 63 },
  { id: 'D2', row: 'D', status: 'free' },
  { id: 'D3', row: 'D', status: 'away', studentName: 'Sneha', checkedInAt: Date.now() - 1000 * 60 * 45, awayAt: Date.now() - 1000 * 60 * 5 },
  { id: 'D4', row: 'D', status: 'free' },
  { id: 'E1', row: 'E', status: 'free' },
  { id: 'E2', row: 'E', status: 'occupied', studentName: 'Vikram', checkedInAt: Date.now() - 1000 * 60 * 35 },
  { id: 'E3', row: 'E', status: 'free' },
  { id: 'E4', row: 'E', status: 'free' },
]